services:
  db:
    image: postgres:16.0-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=killyourselfie
    ports:
      - 5432:5432
    volumes:
      - db:/var/lib/postgresql/data 
 
volumes:
  db:
